version: '3.8'

services:
  # API ASP.NET Core
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reloj-checador-api
    environment:
      ConnectionStrings__DefaultConnection: Server=relojchecador-dbrelojchecador-lkwo1x;Port=3306;Database=mysql;Uid=mysql;Pwd=rg4bjhszrgdruisa;
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
    ports:
      - "5000:8080"
    restart: always
